In [2]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [3]:
randint_1d = torch.randint(-100, 100, (6,))
randint_2d = torch.randint(-100, 100, (6,3))
randint_3d = torch.randint(-100, 100, (6,3, 2))

print(randint_1d, '\n')
print(randint_2d, '\n')
print(randint_3d)

tensor([ 26,  21, -73,  99,  20, -97]) 

tensor([[-61,  46,  38],
        [ 34, -41,   9],
        [-96,  30, -15],
        [-63,  44, -56],
        [-87, -82, -79],
        [ 92, -34, -80]]) 

tensor([[[ 73,  25],
         [-22, -33],
         [ 45,   4]],

        [[-98, -85],
         [ 95, -46],
         [ 36,  92]],

        [[ 61, -43],
         [ 95,   3],
         [ -1,  35]],

        [[-57,  49],
         [  0,  26],
         [-40,  88]],

        [[ 86,  12],
         [-98, -41],
         [ 66,  75]],

        [[ 84,   7],
         [-53,  43],
         [-66,  37]]])


In [4]:
tensor = torch.tensor([[1,2,3], [4,5,6]])
# tensor = tensor.view(3, 3)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3, 4)

In [8]:
# small_float = torch.empty(1, dtype=)

In [7]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00041914
CPU times: user 476 µs, sys: 434 µs, total: 910 µs
Wall time: 683 µs


In [4]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

1.37782574
0.08416343


In [13]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)


# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [15]:
tensor = torch.tensor([1,2,3,4,5])
out = torch.cat((tensor, torch.tensor([10])), dim=0)
out

tensor([ 1,  2,  3,  4,  5, 10])

In [16]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [24]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([  6.1811, -14.4528,   6.1102], grad_fn=<SqueezeBackward4>)


In [5]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.funtional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [6]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)


torch.Size([4, 6])
tensor([[ 1.1844,  1.4478, -0.4377, -1.0174,  1.3985,  0.4654],
        [-0.9652,  0.5983, -0.0124, -1.9301, -0.5542,  0.6121],
        [-1.6841,  0.6114, -1.0348, -2.5228, -1.0145,  0.9897],
        [-1.1846,  0.4179, -0.8162, -1.0067, -0.6297,  0.6683]],
       grad_fn=<EmbeddingBackward0>)


In [7]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [8]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [10]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[0.4605, 0.1075, 0.1498, 0.9993, 0.0506, 0.0398, 0.0386, 0.0586, 0.5195,
         0.2424],
        [0.2050, 0.8847, 0.8112, 0.0163, 0.0024, 0.0604, 0.4690, 0.8693, 0.8643,
         0.5714],
        [0.0394, 0.1117, 0.6585, 0.3117, 0.7191, 0.2439, 0.4411, 0.0356, 0.8903,
         0.3260],
        [0.2612, 0.7656, 0.3167, 0.6475, 0.6378, 0.5157, 0.9187, 0.8572, 0.4828,
         0.4786],
        [0.2250, 0.2256, 0.3330, 0.0263, 0.3873, 0.6214, 0.8987, 0.3628, 0.1286,
         0.5191],
        [0.7292, 0.2665, 0.4950, 0.5210, 0.4071, 0.7910, 0.1010, 0.0463, 0.1283,
         0.2128],
        [0.5882, 0.1487, 0.3149, 0.6153, 0.0727, 0.7695, 0.8536, 0.9090, 0.8741,
         0.9507],
        [0.1716, 0.8645, 0.1626, 0.1005, 0.8754, 0.9951, 0.3292, 0.5198, 0.4321,
         0.4726],
        [0.9766, 0.3431, 0.3474, 0.1016, 0.6246, 0.3880, 0.6860, 0.7520, 0.2758,
         0.3641],
        [0.7141, 0.1520, 0.9630, 0.4740, 0.5908, 0.6140, 0.5695, 0.2905, 0.0071,
         0.7494],
        [0

IndexError: too many indices for tensor of dimension 2

In [11]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
