In [6]:
import torch
import time 

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# print(device)

In [24]:
randint_1d = torch.randint(-100, 100, (6,))
randint_2d = torch.randint(-100, 100, (6,3))
randint_3d = torch.randint(-100, 100, (6,3, 2))

print(randint_1d, '\n')
print(randint_2d, '\n')
print(randint_3d)

tensor([ 11,  -7,   8,  88, -57,  46]) 

tensor([[-75,  38, -87],
        [  3, -48, -82],
        [-93, -51, -36],
        [-24, -84, -88],
        [ 30, -64, -80],
        [ 80,  68,  74]]) 

tensor([[[-26, -47],
         [ 48,  76],
         [-79, -58]],

        [[ 27, -61],
         [-17,  55],
         [-21, -41]],

        [[  4, -12],
         [ 80, -54],
         [ 67,  43]],

        [[ 58, -89],
         [-88, -54],
         [-39,  43]],

        [[-46, -68],
         [ 50,  12],
         [-94,  89]],

        [[-65,  46],
         [ 15,  36],
         [-25, -30]]])


In [30]:
tensor = torch.tensor([[1,2,3], [4,5,6]])
# tensor = tensor.view(3, 3)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [32]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
ones = torch.ones(3, 4)

In [ ]:
small_float = torch.empty(1, dtype=)

In [8]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00006175
CPU times: user 95 µs, sys: 0 ns, total: 95 µs
Wall time: 108 µs
